#!/usr/bin/env cwl-runner

# (Re)generated by BlueBee Platform

$namespaces:
  ilmn-tes: http://platform.illumina.com/rdf/iap/
cwlVersion: cwl:v1.0
class: CommandLineTool
requirements:
- class: ResourceRequirement
  https://platform.illumina.com/rdf/iap/resources:
    type: standard
    size: medium
label: bssh2icav2tool
doc: bssh2icav2tool
inputs:
  metadata_csv:
    type: File
    doc: CSV file containing original and renamed FASTQ files in addition to other
      metadata
    inputBinding:
      position: 1
      prefix: --metadata_table
  input_json:
    type: File
    doc: input JSON from the bssh2json tool
    inputBinding:
      position: 2
      prefix: --input_json
  api_key_file:
    type: File
    inputBinding:
      position: 3
      prefix: --api_key_file
  run_id:
    type: string
    doc: Output folder in data section where results will reside
    inputBinding:
      position: 4
      prefix: --run_id
  project_name:
    type: string
    doc: ICA project name
    inputBinding:
      position: 5
      prefix: --project_name
outputs:
  Output_Dir:
    type:
    - Directory
    - 'null'
    outputBinding:
      glob:
      - $(runtime.outdir)
baseCommand:
- python3
- /data/download_and_upload_to_ICAv2.py
